# Generated by Django 2.1.7 on 2021-01-21 06:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iepl_id', models.CharField(db_column='iepl_id', max_length=10, unique=True)),
                ('service_tag', models.CharField(max_length=100)),
                ('host_name', models.CharField(max_length=100)),
                ('PO_number', models.CharField(max_length=150)),
                ('PO_date', models.DateTimeField(default=datetime.datetime(2021, 1, 21, 6, 48, 35, 205844, tzinfo=utc))),
                ('Model_no', models.CharField(max_length=150)),
                ('desk_no', models.CharField(max_length=50)),
                ('local_admin', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], max_length=50)),
                ('asset_code', models.CharField(default='NA', max_length=100)),
                ('CPU', models.CharField(default='NA', max_length=100)),
                ('CPU_speed', models.CharField(default='NA', max_length=100)),
                ('monitor_model', models.CharField(default='NA', max_length=100)),
                ('OS', models.CharField(default='NA', max_length=100)),
                ('RAM', models.CharField(default='NA', max_length=100)),
                ('HDD', models.CharField(default='NA', max_length=100)),
                ('extra_monitor_model', models.CharField(default='NA', max_length=50)),
                ('Allocation_status', models.CharField(choices=[('Allocated', 'Allocated'), ('Decommissioned', 'Decommissioned'), ('Free', 'Free')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 1, 21, 6, 48, 35, 205844, tzinfo=utc))),
                ('status', models.CharField(default='--', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.EmployeeMaster')),
                ('service_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Item_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('project_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_action', models.CharField(choices=[('Transfer', 'Transfer'), ('Incorrect', 'Incorrect'), ('Return_store', 'Return_store'), ('Free_item', 'Free_item')], max_length=20)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Allocation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.EmployeeMaster')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_action', models.CharField(choices=[('Release', 'Release'), ('Borrow', 'Borrow')], max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.EmployeeMaster')),
                ('service_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Device')),
            ],
        ),
        migrations.CreateModel(
            name='SubsidiaryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Subsidiaries',
            },
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='subsidiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.SubsidiaryMaster'),
        ),
        migrations.AddField(
            model_name='device',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.EmployeeMaster'),
        ),
        migrations.AddField(
            model_name='device',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item_type'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Location'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer'),
        ),
        migrations.AddField(
            model_name='device',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ProjectMaster'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='allot_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.EmployeeMaster'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='service_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Device'),
        ),
    ]
