# Generated by Django 2.1.7 on 2021-01-22 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210121_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='comment',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='PO_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 7, 39, 57, 915106, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 7, 39, 57, 915106, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='history_log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 7, 39, 57, 915106, tzinfo=utc)),
        ),
    ]
