# Generated by Django 3.1.6 on 2021-02-16 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210216_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='PO_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 7, 15, 5, 396883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 7, 15, 5, 397880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='history_log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 7, 15, 5, 402877, tzinfo=utc)),
        ),
    ]
