# Generated by Django 3.1.6 on 2021-03-01 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20210216_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['iepl_id']},
        ),
        migrations.AlterField(
            model_name='device',
            name='PO_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 15, 8, 2, 143467, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 15, 8, 2, 143467, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='history_log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 15, 8, 2, 146465, tzinfo=utc)),
        ),
    ]
