# Generated by Django 3.1.6 on 2021-03-10 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20210301_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='CPU',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='CPU_speed',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='HDD',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='OS',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='PO_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 18, 56, 626934, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='PO_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='RAM',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='allocation_status',
            field=models.CharField(blank=True, choices=[('Allocated', 'Allocated'), ('Decommissioned', 'Decommissioned'), ('Free', 'Free')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='asset_code',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='comment',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 18, 56, 627934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='desk_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.employeemaster'),
        ),
        migrations.AlterField(
            model_name='device',
            name='extra_monitor_model',
            field=models.CharField(blank=True, default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='host_name',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item_type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='local_admin',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.manufacturer'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='monitor_model',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.projectmaster'),
        ),
        migrations.AlterField(
            model_name='device',
            name='service_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='history_log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 18, 56, 635928, tzinfo=utc)),
        ),
    ]
